name: Trigger Meta Repo Update

on:
  workflow_call:


jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger meta repo update workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          token: ${{ secrets.UPDATE_TRIGGER_TOKEN }}
          repository: tsche/re
          workflow: update-submodules.yml
          ref: master