name: Trigger Meta Repo Update

on:
  workflow_call:


jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger meta repo update workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: update.yml
          repo: rsl-org/rsl
          token: "${{ secrets.UPDATE_TRIGGER_TOKEN }}"