name: Update Submodules

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout meta repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.UPDATE_TOKEN }}

      - name: Prepare environment
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "tsche@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.UPDATE_TOKEN }}@github.com/tsche/re.git

      - name: Pull from retest
        run: |
          git remote add retest https://github.com/tsche/retest.git
          git fetch retest master
          git subtree pull --prefix=test retest master
          git push origin master

      - name: Pull from refig
        run: |
          git remote add refig https://github.com/tsche/refig.git
          git fetch refig master
          git subtree pull --prefix=config refig master
          git push origin master
